server:
  port: 9999

# ===== Spring Cloud Gateway =====
spring:

  # ===== Spring Boot =====
  application:
    name: infra-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: modules-players
              uri: lb://modules-players
              predicates:
                - Path=/api/v1/players/**

            - id: modules-users
              uri: lb://modules-users
              predicates:
                - Path=/api/v1/users/**

# ===== Eureka =====
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true