export const goal: string[] = [
  'story/cure_zombie_villager',
  'nether/create_full_beacon',
  'end/dragon_breath',
  'end/dragon_egg',
  'end/respawn_dragon',
  'end/elytra',
  'adventure/totem_of_undying',
  'adventure/spear_many_mobs',
  'adventure/revaulting',
]

export const challenge: string[] = [
  'nether/fast_travel',
  'nether/return_to_sender',
  'nether/netherite_armor',
  'nether/uneasy_alliance',
  'nether/explore_nether',
  'nether/all_potions',
  'nether/all_effects',
  'end/levitate',
  'adventure/kill_all_mobs',
  'adventure/kill_mob_near_sculk_catalyst',
  'adventure/blowback',
  'adventure/overoverkill',
  'adventure / arbalistic',
  'adventure/two_birds_one_arrow',
  'adventure/whos_the_pillager_now',
  'adventure/adventuring_time',
  'adventure/trim_with_all_exclusive_armor_patterns',
  'adventure/hero_of_the_village',
  'adventure/bullseye',
  'adventure/sniper_duel',
  'husbandry/bred_all_animals',
  'husbandry/balanced_diet',
  'husbandry/obtain_netherite_hoe',
  'husbandry/complete_catalogue',
  'husbandry/whole_pack',
  'husbandry/froglights',
]
